services:
  # flask:
  #   build: ./flask
  #   image: edmuhlestein-flask:latest
  #   container_name: flask-edmuhlestein
  #   restart: unless-stopped
  #   expose:
  #     - "5000"
  #   networks:
  #     - ednet

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi-edmuhlestein
    restart: unless-stopped
    expose:
      - "8000"                         # Internal port (no external exposure)
    networks:
      - ednet
    # Optional: environment, volumes, depends_on if needed

networks:
  ednet:
    driver: bridge
