services:

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # Expose FastAPI directly to localhost:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    volumes:
      - ./fastapi/app:/app
    environment:
      - DEBUG=true
    # env_file:
    #   - .env.dev

